### ISSUE TITLE
Cooperate with Omnifaces Arquillian Glassfish project

### ISSUE THREAD

**Issue by hantsy** [arquillian/arquillian-container-glassfish6#17]
I found there is an [arquillian-container-glassfish](https://github.com/omnifaces/arquillian-container-glassfish) under the omnifaces project.

If possible merging effort of https://github.com/omnifaces/arquillian-container-glassfish into this project and provide better experience for Jakarta EE developers. 

It also includes an embedded adapter #9 

@starksm64 @arjantijms

**Comment by starksm64** [comment]
Maybe this should be deprecated in favor of the https://github.com/OmniFish-EE/arquillian-container-glassfish version since the core Arquillian devs don't work on the glassfish project.
